{{- $self := .Values.sof }}
{{- $component := "sof" }}
{{- $name := printf "%s-%s" (include "jhe.fullname" .) $component }}
{{- if $self.enabled }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ $name }}
  labels:
    {{- include "jhe.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := $self.env }}
  {{ $key | quote }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
