jhe:
  # replicas * workers = concurrent request limit
  replicas: 2
  workers: 4
  readinessProbe:
    timeoutSeconds: 10
    periodSeconds: 11
  resources:
    limits:
      cpu: 2
      memory: 700M
    requests:
      cpu: 1
      # testing suggests ~125M per worker
      # 2: 250M
      # 8: 1G
      # 12: 1.4G
      memory: 500M

  coreData:
    assetlinks.json:
      - relation:
          - delegate_permission/common.handle_all_urls
        target:
          namespace: android_app
          package_name: com.jupyter.health.staging
          sha256_cert_fingerprints:
            - "39:7D:A1:A1:A5:B3:26:C1:F1:5A:A5:69:D0:C6:1C:C5:67:47:11:9E:09:93:E2:A5:A5:B2:14:15:FB:07:58:47"
    apple-app-site-association.json:
      applinks:
        details:
          - appIDs:
              - KZJSZ95597.com.jupyter.health
            components:
              - /: /clients/ucsf-edge/*
                comment: UCSF Edge invitation links
  httpRoute:
    hostnames:
      - berkeley-jhe-demo.jupyterhealth.org
  env:
    DJANGO_LOG_LEVEL: DEBUG
    SITE_TITLE: JupyterHealth Exchange Demo
    SITE_URL: https://berkeley-jhe-demo.jupyterhealth.org
  mcp:
    env:
      MCP_RESOURCE_URL: https://mcp.berkeley-jhe-demo.jupyterhealth.org
    httpRoute:
      hostnames:
        - mcp.berkeley-jhe-demo.jupyterhealth.org
  openWearables:
    backend:
      env:
        ADMIN_EMAIL: admin@berkeley-jhe-demo.jupyterhealth.org
        API_BASE_URL: https://ow.berkeley-jhe-demo.jupyterhealth.org
    httpRoute:
      hostnames:
        - ow.berkeley-jhe-demo.jupyterhealth.org

sof:
  httpRoute:
    hostnames:
      - sof.berkeley-jhe-demo.jupyterhealth.org
