version: 2
updates:
  # Maintain dependencies in our GitHub Workflows
  - package-ecosystem: github-actions
    directory: /
    groups:
      # group actions PRs
      official:
        patterns:
          - "actions/*"
      actions:
        patterns:
          - "*"
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
  - package-ecosystem: helm
    directory: /charts/support
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
  - package-ecosystem: helm # zizmor: ignore[dependabot-cooldown]
    directory: /charts/jhe
    schedule:
      interval: daily
