jhe:
  httpRoute:
    hostnames:
      - berkeley-jhe-staging.jupyterhealth.org
  env:
    ALLOWED_HOSTS: localhost,berkeley-jhe-staging.jupyterhealth.org
    DEBUG: "1"
    DJANGO_LOG_LEVEL: DEBUG
    SITE_TITLE: JupyterHealth Exchange (staging)
    SITE_URL: https://berkeley-jhe-staging.jupyterhealth.org
  mcp:
    env:
      MCP_RESOURCE_URL: https://mcp.berkeley-jhe-staging.jupyterhealth.org
    httpRoute:
      hostnames:
        - mcp.berkeley-jhe-staging.jupyterhealth.org
