ci:
  autoupdate_schedule: monthly

repos:
  # autoformat and lint Python code
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.20
    hooks:
      - id: ruff-check
        types_or:
          - python
          - jupyter
        args: ["--fix", "--show-fixes"]
      - id: ruff-format
        types_or:
          - python
          - jupyter

  - repo: https://github.com/hukkin/mdformat
    rev: 1.0.0
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-gfm
          - mdformat-black

  # toml
  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: v0.9.3
    hooks:
      - id: taplo-format

  # yaml
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.9.4
    hooks:
      - id: prettier
        types_or:
          - yaml

  # github actions security checks
  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: e3eebf65325ccc992422292cb7a4baee967cf815 # frozen: v1.26.1
    hooks:
      - id: zizmor
        args:
          - --fix=all

  # github actions
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.12
    hooks:
      - id: actionlint
