apiVersion: v2
name: jhe
version: 0.0.1
description: JupyterHealth Exchange demo
home: https://jupyterhealth.org
sources:
  - https://github.com/jupyterhealth/jupyterhealth-demo-deploy
kubeVersion: ">= 1.32.0-0"
dependencies:
  - name: jhe
    version: 0.0.1-0.dev.git.50.h1eb439e
    repository: oci://ghcr.io/jupyterhealth/helm
