jhe:
  service:
    type: ClusterIP
  httpRoute:
    enabled: true
    parentRefs:
      - name: default
        namespace: support
    filters:
      - type: ExtensionRef
        extensionRef:
          group: gateway.envoyproxy.io
          kind: HTTPRouteFilter
          name: fhir-uppercase
