jhe:
  service:
    type: ClusterIP
  httpRoute:
    enabled: true
    parentRefs:
      - name: default
        namespace: support
  mcp:
    enabled: true
    service:
      type: ClusterIP
    httpRoute:
      enabled: true
      parentRefs:
        - name: default
          namespace: support

  openWearables:
    enabled: true
    httpRoute:
      enabled: true
      parentRefs:
        - name: default
          namespace: support

# in this chart

# smart-on-fhir demo
sof:
  enabled: true
  replicas: 1
  image: ghcr.io/jupyterhealth/sof-cgm-demo:main
  imagePullPolicy: Always
  command: []
  args: []
  resources: {}
  env:
    # common
    SMART_SCOPES: "openid fhirUser launch patient/*.read"
    EHR_IFRAME_ORIGIN: https://app.medplum.com
    MRN_IDENTIFIER_SYSTEM: MedPlumMRN
    SMART_CLIENT_ID: 99d4ba2d-3bc4-40d8-830c-b60d615482ed
    # override in deployments
    JHE_CLIENT_ID: ""
    JHE_CLIENT_SECRET: ""

  podSecurityContext:
    runAsNonRoot: true
    fsGroup: 1000
    seccompProfile:
      type: "RuntimeDefault"
  containerSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]

  httpRoute:
    # -- Expose JHE via Gateway HTTPRoute
    enabled: true
    annotations: {}
    hostnames: []
    parentRefs:
      - name: default
        namespace: support
    timeouts:
      request: 300s
      backendRequest: 0s
  service:
    annotations: {}
