name: deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

concurrency: deploy

jobs:
  deploy:
    runs-on: ubuntu-24.04
    environment: deploy
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6
        with:
          persist-credentials: false

      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6
        with:
          python-version: "3.13"

      - name: install requirements
        run: |
          pip install -r requirements.txt

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e6de054238d6b7531b4efff3b6587d9aade6a06c # v6.2.3
        with:
          role-to-assume: arn:aws:iam::703671906202:role/github-deploy
          aws-region: us-east-2

      - name: install sops
        uses: step-security/mozilla-sops-action@0a79ddf4263479188c0a3a012054bec090ce80bd # v2.1.0

      - name: test decrypt
        run: |
          nox -s decrypt

      - name: update support
        run: |
          nox -s helm_support

      - name: upgrade staging
        run: |
          nox -s helm_jhe
        env:
          JHE_NAME: staging

      - name: upgrade prod
        run: |
          nox -s helm_jhe
        env:
          JHE_NAME: prod
