name: deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

concurrency: deploy

jobs:
  deploy:
    runs-on: ubuntu-24.04
    environment: deploy
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6
        with:
          persist-credentials: false

      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.13"

      - name: install requirements
        run: |
          pip install -r requirements.txt

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e7f100cf4c008499ea8adda475de1042d6975c7b # v6.2.0
        with:
          role-to-assume: arn:aws:iam::703671906202:role/github-deploy
          aws-region: us-east-2

      - name: install sops
        uses: step-security/mozilla-sops-action@3a824d062e37d86cbea2b3cb1d09e84e69447989 # v1

      - name: test decrypt
        run: |
          nox -s decrypt

      - name: update support
        run: |
          nox -s helm_support

      - name: upgrade staging
        run: |
          nox -s helm_jhe
        env:
          JHE_NAME: staging

      - name: upgrade prod
        run: |
          nox -s helm_jhe
        env:
          JHE_NAME: prod
