name: test

on:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6
        with:
          persist-credentials: false

      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v6
        with:
          python-version: "3.13"

      - name: install requirements
        run: |
          pip install -r requirements.txt

      # minimal tests for now, just verify that dependencies exist
      # and chart renders with default values
      - name: test support chart
        run: |
          helm dependency update charts/support
          helm template charts/support

      - name: test jhe chart
        run: |
          helm dependency update charts/jhe
          helm template charts/jhe
